/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed": "#1e1b15",
        "on-tertiary-container": "#36322c",
        "surface": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "tertiary": "#625e56",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#571a00",
        "on-surface-variant": "#584237",
        "surface-container-high": "#e1e8fd",
        "secondary-fixed": "#ffdbce",
        "error-container": "#ffdad6",
        "surface-dim": "#d3daef",
        "surface-container-highest": "#dce2f7",
        "primary-fixed-dim": "#ffb690",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#370e00",
        "primary-fixed": "#ffdbca",
        "tertiary-container": "#a09a91",
        "primary-container": "#f97316",
        "error": "#ba1a1a",
        "inverse-on-surface": "#edf0ff",
        "secondary": "#a73a00",
        "primary": "#9d4300",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#341100",
        "inverse-primary": "#ffb690",
        "secondary-fixed-dim": "#ffb599",
        "on-primary-container": "#582200",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#e9e1d8",
        "on-secondary-fixed-variant": "#7f2b00",
        "tertiary-fixed-dim": "#ccc5bc",
        "surface-variant": "#dce2f7",
        "background": "#f9f9ff",
        "outline-variant": "#e0c0b1",
        "outline": "#8c7164",
        "on-surface": "#141b2b",
        "surface-container": "#e9edff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#4a463f",
        "secondary-container": "#fd651e",
        "on-background": "#141b2b",
        "inverse-surface": "#293040",
        "surface-container-low": "#f1f3ff",
        "on-primary-fixed-variant": "#783200",
        "surface-tint": "#9d4300"
      },
      "borderRadius": {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      "spacing": {
        "container-max": "1280px",
        "base": "8px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "section-gap": "120px"
      },
      "fontFamily": {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
