import { useEffect, useState } from 'react';
import api from '../../services/api';
type Report={id:number;reviewId:number;reasonCode:string;description?:string;status:string};
type Detail={id:number;roomTitle?:string;tenantName:string;contractId?:number;contractStatus?:string;rating?:number;comment?:string;moderationStatus:string;reports:Report[]};
export default function ReviewModeration(){
 const [rows,setRows]=useState<Report[]>([]),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState('');
 const load=async()=>{try{setRows((await api.get('/admin/reviews/reports?page=1&pageSize=50&status=Pending')).data.items)}catch(e:any){setError(e.response?.data?.message||'Không thể tải báo cáo')}};
 useEffect(()=>{load()},[]);
 const act=async(kind:string)=>{if(!detail)return;const reason=prompt('Lý do kiểm duyệt')||'';if(kind==='remove'&&!reason)return;await api.put(`/admin/reviews/${detail.id}/${kind}`,{reason});setDetail(null);load()};
 const dismiss=async(id:number)=>{await api.put(`/admin/review-reports/${id}/dismiss`,{note:'Không phát hiện vi phạm'});setDetail(null);load()};
 return <div className="space-y-4"><h2 className="text-xl font-bold">Kiểm duyệt đánh giá</h2>{error&&<p className="p-3 bg-red-50 text-red-700">{error}</p>}<div className="bg-white rounded-2xl border overflow-hidden"><table className="w-full text-sm"><thead><tr className="bg-gray-50"><th className="p-3">Review</th><th>Lý do</th><th>Mô tả</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3 text-center">#{r.reviewId}</td><td>{r.reasonCode}</td><td>{r.description||'—'}</td><td><button className="text-orange-600 font-bold" onClick={async()=>setDetail((await api.get(`/admin/reviews/${r.reviewId}`)).data)}>Xem evidence</button></td></tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center">Không có báo cáo chờ xử lý.</p>}</div>{detail&&<div className="fixed inset-0 z-50 bg-black/40 grid place-items-center p-4"><div className="bg-white rounded-2xl p-6 max-w-lg w-full space-y-3"><button className="float-right" onClick={()=>setDetail(null)}>✕</button><h3 className="font-bold">Review #{detail.id}</h3><p><b>Phòng:</b> {detail.roomTitle}</p><p><b>Người thuê:</b> {detail.tenantName}</p><p><b>Evidence:</b> Hợp đồng #{detail.contractId} — {detail.contractStatus}</p><p>{detail.rating}/5 — {detail.comment||'Không có nhận xét'}</p><p><b>Trạng thái:</b> {detail.moderationStatus}</p><div className="flex flex-wrap gap-2"><button onClick={()=>act('hide')} className="p-2 bg-amber-100 rounded">Ẩn</button><button onClick={()=>act('remove')} className="p-2 bg-red-600 text-white rounded">Gỡ</button><button onClick={()=>act('restore')} className="p-2 bg-green-600 text-white rounded">Khôi phục</button>{detail.reports.filter(r=>r.status==='Pending').map(r=><button key={r.id} onClick={()=>dismiss(r.id)} className="p-2 bg-gray-100 rounded">Bỏ qua #{r.id}</button>)}</div></div></div>}</div>;
}
