import { useCallback, useEffect, useState } from 'react';
import { viewingApi, type ViewingBooking, type ViewingStatus } from '../services/viewings';
import axios from 'axios';

const labels:Record<string,string>={Pending:'Chờ duyệt',Approved:'Đã duyệt',Rescheduled:'Đề xuất giờ mới',Rejected:'Từ chối',Cancelled:'Đã hủy',Completed:'Đã xem',NoShow:'Không đến',Holding:'Chờ xác nhận',Active:'Đang giữ phòng',Refunded:'Đã hoàn',Forfeited:'Mất cọc',Released:'Đã giải phóng'};
const time=(v?:string)=>v?new Date(v).toLocaleString('vi-VN'):'—';
const errorMessage=(e:unknown)=>axios.isAxiosError<{message?:string}>(e)?e.response?.data?.message||'Không thể thực hiện yêu cầu.':'Không thể thực hiện yêu cầu.';

export default function ViewingBookings({actor}:{actor:'tenant'|'owner'}) {
  const [items,setItems]=useState<ViewingBooking[]>([]); const [status,setStatus]=useState<ViewingStatus|''>(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const result=actor==='tenant'?await viewingApi.tenantList(status||undefined):await viewingApi.ownerList(status||undefined);setItems(result.items);}catch(e){setError(errorMessage(e));}finally{setLoading(false)}},[actor,status]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const run=async(fn:()=>Promise<unknown>)=>{try{await fn();await load()}catch(e){alert(errorMessage(e))}};
  const ownerAction=(b:ViewingBooking,action:string)=>{
    if(action==='reschedule'){const start=prompt('Giờ bắt đầu mới (ISO hoặc YYYY-MM-DDTHH:mm)');const end=prompt('Giờ kết thúc mới');if(!start||!end)return;return run(()=>viewingApi.ownerAction(b.id,action,{startAt:new Date(start).toISOString(),endAt:new Date(end).toISOString(),note:prompt('Ghi chú')||''}));}
    if(action==='reject'){const reason=prompt('Lý do từ chối');if(!reason)return;return run(()=>viewingApi.ownerAction(b.id,action,{reason}));}
    return run(()=>viewingApi.ownerAction(b.id,action));
  };
  const deposit=(b:ViewingBooking)=>{const days=Number(prompt('Số ngày giữ phòng (1-30)','7'));if(!days)return;return run(()=>viewingApi.deposit(b.id, Number(prompt('Tiền cọc (bằng một tháng tiền phòng)')), days, prompt('Phương thức thanh toán','Chuyển khoản')||'Chuyển khoản',prompt('Mã giao dịch (không bắt buộc)')||undefined,prompt('URL minh chứng (không bắt buộc)')||undefined));};
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">Lịch xem phòng & đặt cọc</h2><p className="text-sm text-gray-500">Theo dõi toàn bộ tiến trình, dữ liệu được lưu trên hệ thống.</p></div><select className="border rounded-xl px-3 py-2" value={status} onChange={e=>setStatus(e.target.value as ViewingStatus|'')}><option value="">Tất cả trạng thái</option>{Object.keys(labels).slice(0,7).map(x=><option key={x}>{x}</option>)}</select></div>
    {error&&<div className="p-4 bg-red-50 text-red-700 rounded-xl">{error} <button className="underline" onClick={load}>Thử lại</button></div>}{loading?<div className="p-10 text-center">Đang tải...</div>:items.length===0?<div className="p-10 text-center bg-white rounded-2xl border">Chưa có lịch xem phòng.</div>:<div className="grid gap-4">{items.map(b=><article key={b.id} className="bg-white border rounded-2xl p-5 shadow-sm"><div className="flex justify-between gap-3"><div><h3 className="font-bold">{b.roomTitle}</h3>{actor==='owner'&&<p className="text-sm text-gray-500">Khách: {b.tenantName}</p>}</div><span className="h-fit rounded-full bg-orange-50 text-orange-700 px-3 py-1 text-xs font-bold">{labels[b.status]}</span></div><div className="grid sm:grid-cols-2 gap-2 mt-4 text-sm"><p>Yêu cầu: {time(b.requestedStartAt)} – {time(b.requestedEndAt)}</p><p>Lịch hiện tại: {time(b.scheduledStartAt)} – {time(b.scheduledEndAt)}</p></div>{(b.tenantNote||b.ownerNote||b.rejectReason)&&<p className="mt-3 text-sm text-gray-600">{b.ownerNote||b.rejectReason||b.tenantNote}</p>}
      {b.deposit&&<div className="mt-4 p-3 rounded-xl bg-blue-50 text-sm"><b>Cọc: {b.deposit.amount.toLocaleString('vi-VN')}đ · {labels[b.deposit.status]}</b><div>Hết hạn: {time(b.deposit.expiresAt)}</div>{b.deposit.status==='Active'&&<div className="text-blue-700">Phòng đang được giữ cho bạn.</div>}</div>}
      <div className="flex flex-wrap gap-2 mt-4">{actor==='tenant'&&b.status==='Rescheduled'&&<button className="btn bg-green-600 text-white px-3 py-2 rounded-lg" onClick={()=>run(()=>viewingApi.tenantAction(b.id,'accept-reschedule'))}>Chấp nhận giờ mới</button>}{actor==='tenant'&&['Pending','Rescheduled','Approved'].includes(b.status)&&<button className="px-3 py-2 rounded-lg border" onClick={()=>{const r=prompt('Lý do hủy');if(r)run(()=>viewingApi.tenantAction(b.id,'cancel',r))}}>Hủy lịch</button>}{actor==='tenant'&&['Approved','Completed'].includes(b.status)&&!b.deposit&&<button className="px-3 py-2 rounded-lg bg-orange-600 text-white" onClick={()=>deposit(b)}>Đặt cọc</button>}
      {actor==='owner'&&b.status==='Pending'&&<><button className="px-3 py-2 rounded-lg bg-green-600 text-white" onClick={()=>ownerAction(b,'approve')}>Duyệt</button><button className="px-3 py-2 rounded-lg border" onClick={()=>ownerAction(b,'reschedule')}>Đề xuất giờ</button><button className="px-3 py-2 rounded-lg bg-red-50 text-red-700" onClick={()=>ownerAction(b,'reject')}>Từ chối</button></>}{actor==='owner'&&b.status==='Approved'&&<><button className="px-3 py-2 rounded-lg bg-green-600 text-white" onClick={()=>ownerAction(b,'complete')}>Đã xem</button><button className="px-3 py-2 rounded-lg border" onClick={()=>ownerAction(b,'no-show')}>Không đến</button></>}{actor==='owner'&&b.deposit?.status==='Holding'&&<button className="px-3 py-2 rounded-lg bg-blue-600 text-white" onClick={()=>run(()=>viewingApi.depositAction(b.deposit!.id,'confirm'))}>Xác nhận cọc</button>}{actor==='owner'&&b.deposit&&['Holding','Active'].includes(b.deposit.status)&&<button className="px-3 py-2 rounded-lg border" onClick={()=>run(()=>viewingApi.depositAction(b.deposit!.id,'refund',prompt('Lý do hoàn')||''))}>Hoàn cọc</button>}{actor==='owner'&&b.deposit?.status==='Active'&&<button className="px-3 py-2 rounded-lg bg-red-50 text-red-700" onClick={()=>{const r=prompt('Lý do mất cọc');if(r)run(()=>viewingApi.depositAction(b.deposit!.id,'forfeit',r))}}>Forfeit</button>}</div></article>)}</div>}</div>;
}
